import type { Metadata } from "next";
import { Noto_Serif_Bangali } from "next/font/google";
import "./globals.css";

const notoSarifBangali = Noto_Serif_Bangali({
  subsets: ["latin"]
});



export const metadata: Metadata = {
  title: "আজকের বাজার-দর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return ( 
    <html
      lang="en"
      className={`${notoSarifBangali.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
