import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const notoSarifBangali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});



export const metadata: Metadata = {
  title: "আজকের বাজার-দর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return ( 
    <html
      lang="en"
      data-theme="light"
      className={`${notoSarifBangali.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>
        {children}

        </body>
    </html>
  );
}
